name: Jekyll Site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List root directory contents
      run: ls -R /

    - name: List github workspace contents
      run: ls -R /github/workspace

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Jekyll and Bundler
      run: gem install jekyll bundler

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: List build directory contents
      run: ls -R _site
